# Aplicações para Numpy

Uma das bibliotecas que trabalha diretamente com o Pandas é o Numpy. Esta tem como objetivo realizar manipulações matemáticas em matrizes de forma rápida e eficiente.

Importação da biblioteca:

In [1]:
import numpy as np

In [5]:
one_dim = np.array([1,2,3,4])
type(one_dim)

numpy.ndarray

In [6]:
one_dim.ndim

1

In [7]:
two_dim = np.array([(1,2,3), (4,5,6)])
two_dim.ndim

2

In [8]:
np.random.random((5,2))

array([[0.30494691, 0.21181939],
       [0.58906265, 0.42091735],
       [0.51567548, 0.76662151],
       [0.94067477, 0.86672665],
       [0.4960687 , 0.3790872 ]])

In [9]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
lista = [1,2,3]
lista

[1, 2, 3]

In [13]:
lista*2

[1, 2, 3, 1, 2, 3]

In [15]:
lista = np.array(lista)
type(lista)

numpy.ndarray

In [17]:
lista*2

array([2, 4, 6])

In [19]:
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [23]:
pesos = np.array(pesos)
altura = np.array(altura)

In [25]:
imc = pesos / altura ** 2
imc

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [27]:
a = np.array([1,3,'Casa',True])
a

array(['1', '3', 'Casa', 'True'], dtype='<U11')