# Aplicações para Numpy

Uma das bibliotecas que trabalha diretamente com o Pandas é o Numpy. Esta tem como objetivo realizar manipulações matemáticas em matrizes de forma rápida e eficiente. Outro item que é utilizado em diversos projetos de Machine Learning são os arrays, que possibilitam o cálculo de operações com os conjuntos de números.

Importação da biblioteca:

In [1]:
import numpy as np

Criação de um array unidimensional e apresentação da categoria da variável:

In [2]:
one_dim = np.array([1,2,3,4])
type(one_dim)

numpy.ndarray

Exibição do número de dimensões do array:

In [3]:
one_dim.ndim

1

Criação de array bidimensional e exibição do número de dimensões no array:

In [4]:
two_dim = np.array([(1,2,3), (4,5,6)])
two_dim.ndim

2

Criação de array com valores aleatórios, com duas colunas e cinco linhas:

In [18]:
np.random.random((5,2))

array([[0.94741286, 0.34134739],
       [0.46315707, 0.579094  ],
       [0.16114361, 0.19397006],
       [0.59458147, 0.89517764],
       [0.44763065, 0.93583786]])

Criação de um array que inicia em 10 e termina antes de 50, que cresce em cinco unidades a cada elemento:

In [6]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

Criação de um array linear, iniciando em zero e finalizando em 2, com no máximo 9 elementos:

In [7]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

Criação de um array vazio, com 4 colunas e 3 linhas:

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Criação de listas para cálculo de IMC:

In [13]:
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

Conversão das listas para arrays com Numpy:

In [14]:
pesos = np.array(pesos)
altura = np.array(altura)

Cálculo de IMC com os arrays:

In [15]:
imc = pesos / altura ** 2
imc

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

Apresentação de array com strings e booleanos:

In [16]:
a = np.array([1,3,'Casa',True])
a

array(['1', '3', 'Casa', 'True'], dtype='<U11')

Exibição da quantidade de linhas e colunas:

In [20]:
two_dim.shape

(2, 3)


Exibição do maior valor do array:

In [21]:
two_dim.max()

6

Exibição do menor valor do array:

In [23]:
two_dim.min()

1

Cálculo da média do array:

In [24]:
two_dim.mean()

3.5

Cálculo do desvio padrão do array:

In [25]:
two_dim.std()

1.707825127659933

Exibição da quantidade de elementos no array:

In [26]:
two_dim.size

6

Exibição a quantidade de bites do array:

In [27]:
two_dim.itemsize

4

Soma dos elementos do array:

In [28]:
two_dim.sum()

21

Criação de transposta do array, convertendo as colunas em linhas, e as linhas em colunas:

In [29]:
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

Transformar em uma matriz de uma linha:

In [30]:
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])


Criação de novo array aleatório:

In [32]:
tree = np.random.random((5,3))
tree.shape

(5, 3)

Exibição do array criado:

In [33]:
tree

array([[0.23005952, 0.85202346, 0.79699684],
       [0.38200656, 0.85971998, 0.3178158 ],
       [0.28581067, 0.00819891, 0.83515798],
       [0.58425984, 0.94955523, 0.24730156],
       [0.05737744, 0.10248051, 0.40545304]])

Criação da transposta da nova matriz:

In [34]:
tree.reshape(3,5)

array([[0.23005952, 0.85202346, 0.79699684, 0.38200656, 0.85971998],
       [0.3178158 , 0.28581067, 0.00819891, 0.83515798, 0.58425984],
       [0.94955523, 0.24730156, 0.05737744, 0.10248051, 0.40545304]])

Conversão para array unidimensional:

In [35]:
tree.reshape(-1)

array([0.23005952, 0.85202346, 0.79699684, 0.38200656, 0.85971998,
       0.3178158 , 0.28581067, 0.00819891, 0.83515798, 0.58425984,
       0.94955523, 0.24730156, 0.05737744, 0.10248051, 0.40545304])

Criação de uma variável unidimensional com os dados da variável tree:

In [36]:
t=tree.reshape(1,15)

Adição de elementos a um array:

In [38]:
two_dim = np.insert(two_dim,0,10)
two_dim

array([10, 10,  1,  2,  3,  4,  5,  6])

Remoção de elementos do array:

In [41]:
two_dim = np.delete(two_dim,[0])
two_dim

array([2, 3, 4, 5, 6])

Criação de txt com os valores do array:

In [44]:
np.savetxt("dataset_array.txt",two_dim, delimiter='/')

Criação de array para manipulação:

In [47]:
my_array = np.random.random([10,2])
my_array

array([[0.07320951, 0.01333097],
       [0.24530657, 0.48506957],
       [0.66694779, 0.43996698],
       [0.83923717, 0.6558674 ],
       [0.91108549, 0.25301323],
       [0.85022591, 0.9615618 ],
       [0.31787705, 0.51408283],
       [0.99818152, 0.02229274],
       [0.20051128, 0.36616003],
       [0.99093532, 0.54955077]])

Exibição da primeira linha do array:

In [49]:
my_array[0]

array([0.07320951, 0.01333097])

Exibição do elemento que está na primeira linha e na primeira coluna:

In [50]:
my_array[0][0]

0.07320951179014268

Exibição do elemento que está na primeira linha e na segunda coluna:

In [52]:
my_array[0][1]

0.013330973746186081

Exibição do elemento que está na segunda linha e na segunda coluna:

In [53]:
my_array[1][1]

0.48506956655427713

Exibição do elemento que está na segunda linha e na segunda coluna com outro método:

In [54]:
my_array[1,1]

0.48506956655427713

Exibição até o terceiro valor da segunda coluna:

In [55]:
my_array[:3,1]

array([0.01333097, 0.48506957, 0.43996698])